export const IRONS = [
  {
    name: "Roy Nicolas Bustos Franco",
    cargo: "Secretario Ejecutivo",
    number: "70930853",
    image: "/plancha/nicolas.png",
  },
  {
    name: "Luis Alberto Ordoñez S.",
    cargo: "Ex Secretario Ejecutivo",
    number: "73489045",
    image: "/plancha/ejecutivo.png",
  },
  {
    name: "Lino C. Gonzales Vaca",
    cargo: "Consejero Titular 1",
    number: "75670908",
    image: "/plancha/consejero-titular.png",
  },
  {
    name: "Diego Monasterio M.",
    cargo: "Consejero Suplente 1",
    number: "75515013",
    image: "/plancha/consejero-suplente.png",
  },
  {
    name: "Hector M. Castelo Aguilar",
    cargo: "Consejero Titular 2",
    number: "75013466",
    image: "/plancha/consejero-titular-2.png",
  },
  {
    name: "Mikaela J. Aguilera C.",
    cargo: "Consejero Suplente 2",
    number: "63590629",
    image: "/plancha/consejero-suplente-2.png",
  },
  {
    name: "Blas M. Mérida H.",
    cargo: "Secretario Académico",
    number: "69069051",
    image: "/plancha/secretario-academico.png",
  },
  {
    name: "Areli Marquez A.",
    cargo: "Secretaria De Hacienda",
    number: "73304321",
    image: "/plancha/secretaria-de-acienda.png",
  },
  {
    name: "Ximena Chambi H.",
    cargo: "Secretaria Del Bienestar Estudiantil",
    number: "73140887",
    image: "/plancha/secretaria-del-bienestar-estudiantil.png",
  },
  {
    name: "J. Yhery Herrera M.",
    cargo: "Secretario De Conflictos",
    number: "73687945",
    image: "/plancha/secretario-de-conflictos.png",
  },
  {
    name: "Daneyva A. Borda G.",
    cargo: "Secretaria De Prensa",
    number: "79006658",
    image: "/plancha/secretaria-de-prensa.png",
  },
  {
    name: "J. Junior Vargas Mena",
    cargo: "Secretario De Extensión",
    number: "60917792",
    image: "/plancha/secretario-de-extension.png",
  },
  {
    name: "Paul A. Molina Vaca",
    cargo: "Secretario De Deportes",
    number: "71014608",
    image: "/plancha/secretario-de-deporte.png",
  },
  {
    name: "M. Andrea Colombo T.",
    cargo: "Secretaria De Relaciones",
    number: "77688401",
    image: "/plancha/secretaria-de-relaciones.png",
  },
  {
    name: "Melanie Bustillos V.",
    cargo: "Secretaria De Recursos Naturales",
    number: "76947490",
    image: "/plancha/secretaria-de-recursos-naturales.png",
  },
  {
    name: "Ivon Urquizu Callejas",
    cargo: "Vocal 1",
    number: "62032359",
    image: "/plancha/vocal-1.png",
  },
  {
    name: "Paola Rojas Sirpa",
    cargo: "Vocal 2",
    number: "75018924",
    image: "/plancha/vocal-2.png",
  },
  {
    name: "Evita C. Rivero U.",
    cargo: "Vocal 3",
    number: "67996474",
    image: "/plancha/vocal-3.png",
  },
  {
    name: "Cristian Torrez B.",
    cargo: "Vocal 4",
    number: "76300752",
    image: "/plancha/vocal-4.png",
  },
  {
    name: "R. Halley Siles Nuñez",
    cargo: "Vocal 5",
    number: "70037868",
    image: "/plancha/vocal-5.png",
  },
  {
    name: "Robert Neyl Kababat M.",
    cargo: "Vocal 6",
    number: "75088035",
    image: "/plancha/vocal-6.png",
  },
  {
    name: "Jhair André Miranda",
    cargo: "Vocal 7",
    number: "69277273",
    image: "/plancha/vocal-7.png",
  },
  {
    name: "Josue Husai Gonzales M.",
    cargo: "Vocal 8",
    number: "71059581",
    image: "/plancha/vocal-8.png",
  },
  {
    name: "A. Lucas Muruchi Lequipe",
    cargo: "Adscrito 1",
    number: "67799669",
    image: "/plancha/adscrito-1.png",
  },
];