export const SUBJECTS = [
  // Primer año
  {
    id: 1,
    name: "Formación Sociocultural Boliviana",
    path: "formacion-sociocultural-boliviana",
    sigla: "MAF 100",
    year: 1,
    semester: true,
    multigrupo: false,
    teachers: [
      {
        id: 34,
        name: "Rivero Bolívar Harold Percy",
        path: "rivero-bolivar-harold-percy",
      },
      { id: 59, name: "Lic. Reymi Ferreira", path: "lic-reymi-ferreira" },
    ],
  },
  {
    id: 2,
    name: "Anatomía Humana",
    path: "anatomia-humana",
    sigla: "MED 100",
    year: 1,
    semester: false,
    multigrupo: true,
    teachers: [
      { id: 1, name: "Aguilar Gonzales Oscar", path: "aguilar-gonzales-oscar" },
      {
        id: 12,
        name: "Dorado Quesada Pedro Rodolfo",
        path: "dorado-quesada-pedro-rodolfo",
      },
      { id: 29, name: "Pedraza Leaños Raúl", path: "pedraza-leanos-raul" },
      { id: 37, name: "Sossa Lino José Luis", path: "sossa-lino-jose-luis" },
    ],
  },
  {
    id: 3,
    name: "Histología y Embriología",
    path: "histologia-y-embriologia",
    sigla: "MED 101",
    year: 1,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 16,
        name: "Iriarte Céspedes Norberto",
        path: "iriarte-cespedes-norberto",
      },
      {
        id: 18,
        name: "Laguna Montaño Raúl Jhonny",
        path: "laguna-montano-raul-jhonny",
      },
      {
        id: 34,
        name: "Rivero Bolívar Harold Percy",
        path: "rivero-bolivar-harold-percy",
      },
      { id: 58, name: "Sánchez Araos Darío", path: "sanchez-araos-dario" },
      {
        id: 36,
        name: "Sangüeza Acosta Ariel Lionel",
        path: "sangueza-acosta-ariel-lionel",
      },
    ],
  },
  {
    id: 4,
    name: "Salud Pública 1",
    path: "salud-publica-1",
    sigla: "SAP 100",
    year: 1,
    semester: true,
    multigrupo: false,
    teachers: [
      {
        id: 33,
        name: "Rivera Márquez Williams Pedro",
        path: "rivera-marquez-williams-pedro",
      },
      {
        id: 34,
        name: "Rivero Bolívar Harold Percy",
        path: "rivero-bolivar-harold-percy",
      },
    ],
  },

  // Segundo año
  {
    id: 5,
    name: "Bioquímica Médica",
    path: "bioquimica-medica",
    sigla: "MED 203",
    year: 2,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 15,
        name: "Hidalgo Filipavichi María Elizabeth",
        path: "hidalgo-filipavichi-maria-elizabeth",
      },
      { id: 30, name: "Pinto Guevara Yandira", path: "pinto-guevara-yandira" },
      { id: 31, name: "Quiróz Peña Martha", path: "quiroz-pena-martha" },
    ],
  },
  {
    id: 6,
    name: "Fisiología Humana",
    path: "fisiologia-humana",
    sigla: "MED 202",
    year: 2,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 22,
        name: "Méndez Capovianco Alberto",
        path: "mendez-capovianco-alberto",
      },
      {
        id: 24,
        name: "Nogales Stresic Edmundo Hilario",
        path: "nogales-stresic-edmundo-hilario",
      },
      {
        id: 33,
        name: "Rivera Márquez Williams Pedro",
        path: "rivera-marquez-williams-pedro",
      },
    ],
  },
  {
    id: 7,
    name: "Anatomía Patológica",
    path: "anatomia-patologica",
    sigla: "MED 200",
    year: 2,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 20,
        name: "Machado Justiniano Juan José",
        path: "machado-justiniano-juan-jose",
      },
      {
        id: 36,
        name: "Sangüeza Acosta Ariel Lionel",
        path: "sangueza-acosta-ariel-lionel",
      },
    ],
  },
  {
    id: 8,
    name: "Bacteriología y Virología Humana",
    path: "bacteriologia-y-virologia-humana",
    sigla: "MED 201",
    year: 2,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 3,
        name: "Arauz Barba María Elena",
        path: "arauz-barba-maria-elena",
      },
      {
        id: 8,
        name: "Chely de Limpias Elizabeth",
        path: "chely-de-limpias-elizabeth",
      },
      { id: 38, name: "Tapia Ríos Carmela", path: "tapia-rios-carmela" },
    ],
  },
  {
    id: 9,
    name: "Parasitología y Micología Médica",
    path: "parasitologia-y-micologia-medica",
    sigla: "MED 209",
    year: 2,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 3,
        name: "Arauz Barba María Elena",
        path: "arauz-barba-maria-elena",
      },
      {
        id: 10,
        name: "Cuéllar Landívar Walter Hugo",
        path: "cuellar-landivar-walter-hugo",
      },
      { id: 27, name: "Ortiz Céspedes Daniel", path: "ortiz-cespedes-daniel" },
      { id: 31, name: "Quiróz Peña Martha", path: "quiroz-pena-martha" },
      {
        id: 35,
        name: "saavedra quintanilla juan A.",
        path: "saavedra-quintanilla-juan-a",
      },
    ],
  },
  {
    id: 10,
    name: "Salud Pública 2",
    path: "salud-publica-2",
    sigla: "SAP 200",
    year: 2,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 19,
        name: "Leaños Hereria Hernán Omar",
        path: "leanos-hereria-hernan-omar",
      },
      {
        id: 45,
        name: "Tomas Virgilio Prieto Barrón",
        path: "tomas-virgilio-prieto-barron",
      },
    ],
  },

  // Tercer año
  {
    id: 11,
    name: "Farmacología y Terapéutica",
    path: "farmacologia-y-terapeutica",
    sigla: "MED 303",
    year: 3,
    semester: false,
    multigrupo: false,
    teachers: [
      { id: 11, name: "Dajer Ulloa Erika", path: "dajer-ulloa-erika" },
      {
        id: 40,
        name: "Von Borries Kovac Hugo",
        path: "von-borries-kovac-hugo",
      },
    ],
  },
  {
    id: 12,
    name: "Cirugía 1",
    path: "cirugia-1",
    sigla: "CIR 305",
    year: 3,
    semester: false,
    multigrupo: true,
    teachers: [
      { id: 1, name: "Aguilar Gonzales Oscar", path: "aguilar-gonzales-oscar" },
      { id: 9, name: "Coronado Guzmán Jorge", path: "coronado-guzman-jorge" },
    ],
  },
  {
    id: 13,
    name: "Fisiopatología",
    path: "fisiopatologia",
    sigla: "MED 301",
    year: 3,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 2,
        name: "Aguilar Justiniano Javier Oscar",
        path: "aguilar-justiniano-javier-oscar",
      },
      {
        id: 12,
        name: "Dorado Quesada Pedro Rodolfo",
        path: "dorado-quesada-pedro-rodolfo",
      },
      {
        id: 21,
        name: "Maida Vargas de Morales Tatiana",
        path: "maida-vargas-de-morales-tatiana",
      },
    ],
  },
  {
    id: 14,
    name: "Semiología General",
    path: "semiologia-general",
    sigla: "MED 302",
    year: 3,
    semester: false,
    multigrupo: true,
    teachers: [
      {
        id: 4,
        name: "Arce Justiniano Jorge Ronald",
        path: "arce-justiniano-jorge-ronald",
      },
      {
        id: 28,
        name: "Panoso Gonzales Katty Olivia",
        path: "panoso-gonzales-katty-olivia",
      },
      {
        id: 39,
        name: "Terrazas Gómez Héctor Mirko",
        path: "terrazas-gomez-hector-mirko",
      },
    ],
  },
  {
    id: 15,
    name: "Infectología y Medicina Tropical",
    path: "infectologia-y-medicina-tropical",
    sigla: "MED 304",
    year: 3,
    semester: false,
    multigrupo: true,
    teachers: [
      {
        id: 35,
        name: "Saavedra Quintanilla Juan A.",
        path: "saavedra-quintanilla-juan-a",
      },
    ],
  },
  {
    id: 16,
    name: "Salud Pública 3",
    path: "salud-publica-3",
    sigla: "SAP 300",
    year: 3,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 22,
        name: "Méndez Capovianco Alberto",
        path: "mendez-capovianco-alberto",
      },
      { id: 58, name: "Sánchez Araos Darío", path: "sanchez-araos-dario" },
      {
        id: 41,
        name: "Zambrana Balladares Lilian",
        path: "zambrana-balladares-lilian",
      },
    ],
  },

  // Cuarto año
  {
    id: 17,
    name: "Anestesiología",
    path: "anestesiologia",
    sigla: "MED 403",
    year: 4,
    semester: true,
    multigrupo: false,
    teachers: [
      {
        id: 25,
        name: "Oropeza Claure José Adolfo",
        path: "oropeza-claure-jose-adolfo",
      },
      { id: 7, name: "Carlos Iván Quiroga", path: "carlos-ivan-quiroga" },
    ],
  },
  {
    id: 18,
    name: "Oftalmología",
    path: "oftalmologia",
    sigla: "CIR 402",
    year: 4,
    semester: true,
    multigrupo: false,
    teachers: [
      { id: 23, name: "Molina Mery Rafael", path: "molina-mery-rafael" },
    ],
  },
  {
    id: 19,
    name: "Cirugía 2",
    path: "cirugia-2",
    sigla: "CIR 400",
    year: 4,
    semester: false,
    multigrupo: true,
    teachers: [
      {
        id: 5,
        name: "Aponte Vargas José Luis",
        path: "aponte-vargas-jose-luis",
      },
      {
        id: 14,
        name: "Flores Reus Ral Eduardo",
        path: "flores-reus-ral-eduardo",
      },
      {
        id: 57,
        name: "Vargas Vanegas Reinerio",
        path: "vargas-vanegas-reinerio",
      },
      { id: 56, name: "Viruez Soleto Erwin", path: "viruez-soleto-erwin" },
    ],
  },
  {
    id: 20,
    name: "Traumatología y Ortopedia",
    path: "traumatologia-y-ortopedia",
    sigla: "CIR 401",
    year: 4,
    semester: true,
    multigrupo: false,
    teachers: [
      { id: 29, name: "Pedraza Leaños Raúl", path: "pedraza-leanos-raul" },
      { id: 55, name: "Edgar Sempertegui", path: "edgar-sempertegui" },
    ],
  },
  {
    id: 21,
    name: "Medicina Interna 1",
    path: "medicina-interna-1",
    sigla: "MED 400",
    year: 4,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 54,
        name: "Javier Alfredo Alcazar Almeida",
        path: "javier-alfredo-alcazar-almeida",
      },
      {
        id: 53,
        name: "Omar Montero Gandarilla",
        path: "omar-montero-gandarilla",
      },
      { id: 52, name: "Germán Toledo", path: "german-toledo" },
    ],
  },
  {
    id: 22,
    name: "Neurología",
    path: "neurologia",
    sigla: "MED 405",
    year: 4,
    semester: true,
    multigrupo: false,
    teachers: [
      {
        id: 49,
        name: "salas ferrufino gueider",
        path: "salas-ferrufino-gueider",
      },
      {
        id: 26,
        name: "Osinaga García Remberto",
        path: "osinaga-garcia-remberto",
      },
    ],
  },
  {
    id: 23,
    name: "Psicopatología",
    path: "psicopatologia",
    sigla: "MED 415",
    year: 4,
    semester: true,
    multigrupo: false,
    teachers: [
      {
        id: 42,
        name: "David schusselberg chavez",
        path: "david-schusselberg-chavez",
      },
      {
        id: 43,
        name: "Elva Soto Sanchez de Montero",
        path: "elva-soto-sanchez-de-montero",
      },
    ],
  },
  {
    id: 24,
    name: "Dermatología",
    path: "dermatologia",
    sigla: "MED 413",
    year: 4,
    semester: true,
    multigrupo: false,
    teachers: [
      {
        id: 44,
        name: "Maria Pavez Lizarraga de Aranzazu",
        path: "maria-pavez-lizarraga-de-aranzazu",
      },
    ],
  },
  {
    id: 25,
    name: "Salud Pública 4",
    path: "salud-publica-4",
    sigla: "SAP 400",
    year: 4,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 45,
        name: "Tomas Virgilio Prieto Barron",
        path: "tomas-virgilio-prieto-barron",
      },
    ],
  },

  // Quinto año
  {
    id: 26,
    name: "Cirugía 3",
    path: "cirugia-3",
    sigla: "CIR 500",
    year: 5,
    semester: false,
    multigrupo: true,
    teachers: [
      {
        id: 5,
        name: "Aponte Vargas José Luis",
        path: "aponte-vargas-jose-luis",
      },
      {
        id: 14,
        name: "Flores Reus Ral Eduardo",
        path: "flores-reus-ral-eduardo",
      },
      {
        id: 57,
        name: "Vargas Vanegas Reinerio",
        path: "vargas-vanegas-reinerio",
      },
      { id: 56, name: "Viruez Soleto Erwin", path: "viruez-soleto-erwin" },
      {
        id: 62,
        name: "Jorge Fernando Aparicio",
        path: "jorge-fernando-aparicio",
      },
    ],
  },
  {
    id: 27,
    name: "Ginecología y Obstetricia",
    path: "ginecologia-y-obstetricia",
    sigla: "CIR 505",
    year: 5,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 46,
        name: "Edgar Caballero Ibañez",
        path: "edgar-caballero-ibanez",
      },
      {
        id: 13,
        name: "Encinas Justiniano Leoncio",
        path: "encinas-justiniano-leoncio",
      },
      { id: 47, name: "Jesus Rodolfo Serrano", path: "jesus-rodolfo-serrano" },
    ],
  },
  {
    id: 28,
    name: "Pediatría",
    path: "pediatria",
    sigla: "MED 504",
    year: 5,
    semester: false,
    multigrupo: true,
    teachers: [
      {
        id: 6,
        name: "Bolívar Guzmán Rubén Darío",
        path: "bolivar-guzman-ruben-dario",
      },
      { id: 32, name: "Rivas Soruco Felipe", path: "rivas-soruco-felipe" },
    ],
  },
  {
    id: 29,
    name: "Medicina Interna 2",
    path: "medicina-interna-2",
    sigla: "MED 500",
    year: 5,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 51,
        name: "Victor Hugo Vargas Pereira",
        path: "victor-hugo-vargas-pereira",
      },
      {
        id: 50,
        name: "Marcelo Mendez Rosales",
        path: "marcelo-mendez-rosales",
      },
      { id: 60, name: "wilfredo anzoategui", path: "wilfredo-anzoategui" },
      { id: 61, name: "grover aguilar", path: "grover-aguilar" },
    ],
  },
  {
    id: 30,
    name: "Otorinolaringología",
    path: "otorinolaringologia",
    sigla: "CIR 506",
    year: 5,
    semester: true,
    multigrupo: false,
    teachers: [
      {
        id: 17,
        name: "israel araujo yuself jail",
        path: "israel-araujo-yuself-jail",
      },
    ],
  },
  {
    id: 31,
    name: "Psiquiatría y Salud Mental",
    path: "psiquiatria-y-salud-mental",
    sigla: "MED 501",
    year: 5,
    semester: true,
    multigrupo: false,
    teachers: [
      {
        id: 42,
        name: "David schusselberg chavez",
        path: "david-schusselberg-chavez",
      },
      { id: 48, name: "Elba soto Sanchez", path: "elba-soto-sanchez" },
    ],
  },
  {
    id: 32,
    name: "Medicina Legal",
    path: "medicina-legal",
    sigla: "MED 508",
    year: 5,
    semester: false,
    multigrupo: false,
    teachers: [
      {
        id: 49,
        name: "Haroldo Mendez de la Fuente",
        path: "haroldo-mendez-de-la-fuente",
      },
    ],
  },
];
